id: P000231
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །འཇམ་དབྱངས་སྤྲུལ་པའི་གླེགས་བམ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  layers:
  - book_title
  - author
  - quotation
  - yigchung
  id: SHE-SHAP-08
web_metadata:
  title:
    en: The Book of Emanated Scripture of Manjushri
    bo: འཇམ་དབྱངས་སྤྲུལ་པའི་གླེགས་བམ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 8
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༨
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-08
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-08.epub
  description:
    en: ''
    bo: ''
